#!/usr/bin/env sh

YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'  # No Color
current_branch=$(git rev-parse --abbrev-ref HEAD)

message="\n\n🔴  ${YELLOW}ERROR - You must create a Pull Request to be able to merge code into main branches${NC}\n\n"

case "$current_branch" in
  "dev" | "qa" | "prod" | "main" | "pre-prod" )
    echo "$message"
    exit 1
    ;;
  * )
    exit 0
    ;;
esac